# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import decision_ledger_pb2 as decision__ledger__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in decision_ledger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DecisionLedgerServiceStub:
    """Bi-Directional High-Throughput Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_unary(
                '/decision_ledger.DecisionLedgerService/StreamTelemetry',
                request_serializer=decision__ledger__pb2.TelemetryRecord.SerializeToString,
                response_deserializer=decision__ledger__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.StreamPolicyUpdates = channel.unary_stream(
                '/decision_ledger.DecisionLedgerService/StreamPolicyUpdates',
                request_serializer=decision__ledger__pb2.PolicyRequest.SerializeToString,
                response_deserializer=decision__ledger__pb2.PolicyUpdate.FromString,
                _registered_method=True)
        self.BiDirectionalSync = channel.stream_stream(
                '/decision_ledger.DecisionLedgerService/BiDirectionalSync',
                request_serializer=decision__ledger__pb2.TelemetryRecord.SerializeToString,
                response_deserializer=decision__ledger__pb2.PolicyUpdate.FromString,
                _registered_method=True)


class DecisionLedgerServiceServicer:
    """Bi-Directional High-Throughput Service Definition
    """

    def StreamTelemetry(self, request_iterator, context):
        """Stream telemetry records from client microservices to server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPolicyUpdates(self, request, context):
        """Stream policy updates from server to client nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BiDirectionalSync(self, request_iterator, context):
        """Bi-directional full-duplex telemetry and policy sync stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionLedgerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=decision__ledger__pb2.TelemetryRecord.FromString,
                    response_serializer=decision__ledger__pb2.TelemetryResponse.SerializeToString,
            ),
            'StreamPolicyUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPolicyUpdates,
                    request_deserializer=decision__ledger__pb2.PolicyRequest.FromString,
                    response_serializer=decision__ledger__pb2.PolicyUpdate.SerializeToString,
            ),
            'BiDirectionalSync': grpc.stream_stream_rpc_method_handler(
                    servicer.BiDirectionalSync,
                    request_deserializer=decision__ledger__pb2.TelemetryRecord.FromString,
                    response_serializer=decision__ledger__pb2.PolicyUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'decision_ledger.DecisionLedgerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('decision_ledger.DecisionLedgerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecisionLedgerService:
    """Bi-Directional High-Throughput Service Definition
    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/decision_ledger.DecisionLedgerService/StreamTelemetry',
            decision__ledger__pb2.TelemetryRecord.SerializeToString,
            decision__ledger__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPolicyUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/decision_ledger.DecisionLedgerService/StreamPolicyUpdates',
            decision__ledger__pb2.PolicyRequest.SerializeToString,
            decision__ledger__pb2.PolicyUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BiDirectionalSync(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/decision_ledger.DecisionLedgerService/BiDirectionalSync',
            decision__ledger__pb2.TelemetryRecord.SerializeToString,
            decision__ledger__pb2.PolicyUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
