# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: decision_ledger.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'decision_ledger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x65\x63ision_ledger.proto\x12\x0f\x64\x65\x63ision_ledger\"\xc3\x01\n\x0fTelemetryRecord\x12\x13\n\x0b\x64\x65\x63ision_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontext_hash\x18\x02 \x01(\x0c\x12\x18\n\x10model_confidence\x18\x03 \x01(\x01\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\x05\x12\x15\n\rdecision_type\x18\x05 \x01(\t\x12\x12\n\nlatency_ns\x18\x06 \x01(\x03\x12\x14\n\x0ctimestamp_ns\x18\x07 \x01(\x03\x12\x11\n\x04loss\x18\x08 \x01(\x01H\x00\x88\x01\x01\x42\x07\n\x05_loss\"V\n\x0eTelemetryBatch\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x31\n\x07records\x18\x02 \x03(\x0b\x32 .decision_ledger.TelemetryRecord\"T\n\x11TelemetryResponse\x12\x17\n\x0fprocessed_count\x18\x01 \x01(\x03\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"B\n\rPolicyRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x1e\n\x16\x63urrent_policy_version\x18\x02 \x01(\t\"i\n\x0f\x43ontextEnvelope\x12\r\n\x05q_hat\x18\x01 \x01(\x01\x12\x17\n\x0fmin_sample_size\x18\x02 \x01(\x05\x12\x1b\n\x13\x63urrent_sample_size\x18\x03 \x01(\x05\x12\x11\n\tis_active\x18\x04 \x01(\x08\"\xe9\x01\n\x0cPolicyUpdate\x12\x16\n\x0epolicy_version\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x03\x12=\n\x08\x63ontexts\x18\x03 \x03(\x0b\x32+.decision_ledger.PolicyUpdate.ContextsEntry\x12\x19\n\x11\x65\x64\x32\x35\x35\x31\x39_signature\x18\x04 \x01(\x0c\x1aQ\n\rContextsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .decision_ledger.ContextEnvelope:\x02\x38\x01\x32\xa4\x02\n\x15\x44\x65\x63isionLedgerService\x12Y\n\x0fStreamTelemetry\x12 .decision_ledger.TelemetryRecord\x1a\".decision_ledger.TelemetryResponse(\x01\x12V\n\x13StreamPolicyUpdates\x12\x1e.decision_ledger.PolicyRequest\x1a\x1d.decision_ledger.PolicyUpdate0\x01\x12X\n\x11\x42iDirectionalSync\x12 .decision_ledger.TelemetryRecord\x1a\x1d.decision_ledger.PolicyUpdate(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'decision_ledger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POLICYUPDATE_CONTEXTSENTRY']._loaded_options = None
  _globals['_POLICYUPDATE_CONTEXTSENTRY']._serialized_options = b'8\001'
  _globals['_TELEMETRYRECORD']._serialized_start=43
  _globals['_TELEMETRYRECORD']._serialized_end=238
  _globals['_TELEMETRYBATCH']._serialized_start=240
  _globals['_TELEMETRYBATCH']._serialized_end=326
  _globals['_TELEMETRYRESPONSE']._serialized_start=328
  _globals['_TELEMETRYRESPONSE']._serialized_end=412
  _globals['_POLICYREQUEST']._serialized_start=414
  _globals['_POLICYREQUEST']._serialized_end=480
  _globals['_CONTEXTENVELOPE']._serialized_start=482
  _globals['_CONTEXTENVELOPE']._serialized_end=587
  _globals['_POLICYUPDATE']._serialized_start=590
  _globals['_POLICYUPDATE']._serialized_end=823
  _globals['_POLICYUPDATE_CONTEXTSENTRY']._serialized_start=742
  _globals['_POLICYUPDATE_CONTEXTSENTRY']._serialized_end=823
  _globals['_DECISIONLEDGERSERVICE']._serialized_start=826
  _globals['_DECISIONLEDGERSERVICE']._serialized_end=1118
# @@protoc_insertion_point(module_scope)
